// Auto-generated by `npm run supabase:types` after schema is in place.
// DO NOT EDIT MANUALLY — regeneration will overwrite.
//
// Until task 04-30-supabase-init lands, use the placeholder below so the
// frontend type-checks. It models a minimal shape based on docs/TECH_SPEC.md §2.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
