// Auto-generated by `npm run supabase:types` after the Supabase project lands.
// DO NOT EDIT MANUALLY — regeneration will overwrite.
//
// Until that runs against the real project, this hand-rolled placeholder
// models the minimal shape the frontend needs based on
// `supabase/migrations/0001_init.sql` + `0003_support_tickets.sql`. Keep it
// loose (jsonb fields as `unknown`) — the real types will be exact.

type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

type Timestamps = {
  created_at: string
  updated_at: string
}

type ChartRow = Timestamps & {
  id: string
  user_id: string
  type: string
  title: string
  input_data: Json
  input_meta: Json | null
  chart_data: Json
  is_favorite: boolean
  birth_time_encrypted: string | null
  birth_place_encrypted: string | null
}

type ReadingRow = Timestamps & {
  id: string
  user_id: string
  chart_id: string
  scene: string
  prompt_version: string
  status: string
  model: string | null
  question: string | null
  content: string | null
  cost_usd: number | null
  quality_score: number | null
  rating: 1 | 2 | 3 | 4 | 5 | null
  rated_at: string | null
}

type ReportRow = Timestamps & {
  id: string
  user_id: string
  chart_id: string
  type: string
  status: string
  progress: number
  amount_usd: number | null
  refund_amount_usd: number | null
  storage_path: string | null
  signed_url_expires_at: string | null
  user_rating: 1 | 2 | 3 | 4 | 5 | null
  user_feedback: string | null
  error_message: string | null
}

type SubscriptionRow = Timestamps & {
  id: string
  user_id: string
  tier: 'free' | 'plus' | 'pro'
  status: string
  stripe_customer_id: string | null
  stripe_subscription_id: string | null
  current_period_end: string | null
}

type SupportTicketRow = Timestamps & {
  id: string
  user_id: string
  channel: string
  category: string
  priority: number
  status: string
  subject: string
  initial_body: string
  replies: Json
  related_reading_id: string | null
  related_report_id: string | null
  first_reply_at: string | null
  closed_at: string | null
}

type Insertable<T> = Partial<T> & { user_id: string }
type Updatable<T> = Partial<T>

type Tbl<R> = { Row: R; Insert: Insertable<R>; Update: Updatable<R>; Relationships: [] }

export type Database = {
  public: {
    Tables: {
      charts: Tbl<ChartRow>
      readings: Tbl<ReadingRow>
      reports: Tbl<ReportRow>
      subscriptions: Tbl<SubscriptionRow>
      support_tickets: Tbl<SupportTicketRow>
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
